name: test_env
channels:
- conda-forge
dependencies:
- cython
- filelock
- h5py >=2.3
- imageio >=2.16
- numba >=0.52
- pooch
- pytest
- pytest-xdist
- pytest-rerunfailures
- hyperspy-base >=2.0
- setuptools-scm
- sparse
- tifffile>=2022.7.28
- zarr
